# Generated by Django 4.2.7 on 2024-02-05 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BookId', models.CharField(max_length=200)),
                ('BookName', models.CharField(max_length=200)),
                ('Author', models.CharField(max_length=200)),
                ('BookStatus', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='user_new',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=200)),
                ('Email', models.CharField(max_length=200)),
                ('Register_number', models.CharField(max_length=200)),
                ('Login_as', models.CharField(choices=[('Admin', 'Admin'), ('User', 'User'), ('Librarian', 'Librarian')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='user_with_books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BookId', models.CharField(max_length=200)),
                ('Register_number', models.CharField(max_length=200)),
                ('IssuedOn', models.DateField()),
                ('ReturnedOn', models.DateField(null=True)),
                ('Fine', models.CharField(max_length=200)),
            ],
        ),
    ]
