# Generated by Django 4.2.7 on 2024-01-30 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0002_user_new_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bookname', models.CharField(max_length=200)),
                ('Bookid', models.IntegerField()),
                ('BookAuthor', models.CharField(max_length=200)),
                ('BookStatus', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='user_new',
            name='Login_as',
            field=models.CharField(choices=[('Admin', 'Admin'), ('User', 'User'), ('Librarian', 'Librarian')], max_length=200),
        ),
    ]
