# Generated by Django 4.2.7 on 2024-01-30 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0003_books_alter_user_new_login_as'),
    ]

    operations = [
        migrations.CreateModel(
            name='books_with_users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bookname', models.CharField(max_length=200)),
                ('Bookid', models.IntegerField()),
                ('Userid', models.IntegerField()),
                ('IssuedOn', models.DateField()),
                ('ReturnedOn', models.DateField()),
                ('Penalty', models.IntegerField()),
            ],
        ),
    ]
